# Site settings
title: Startup Institute Berlin - Web Design Track 2015
email: talk@nan.do
description: > # this means to ignore newlines until "baseurl:"
  My take on the front-end development content of Startup
  Institute's Web Design Track.

baseurl: "/SIBer-WebDesign2015" # the subpath of your site, e.g. /blog/
url: "http://nandorocker.github.io" # the base hostname & protocol for your site
# url: http://localhost:4000
permalink: none
twitter_username: nandorocker
github_username:  nandorocker

# Build settings
markdown: redcarpet
encoding: utf-8